### PR TITLE
deals with Brightcookie/lxHive-Internal#86, user validation

### PR DESCRIPTION
**Pull request by RoboSparrow**
simplified email and password validation for ./X user:create

### CODE REVIEW

**Comment by RoboSparrow** [comment]
https://github.com/Brightcookie/lxHive-Internal/issues/86

**Comment by RoboSparrow** [comment]
cs-fixes in https://github.com/Brightcookie/lxHive/pull/145

**Comment by RoboSparrow** [comment]
@sraka1 ?

**Comment by sraka1** [comment]
Closing this as all commits are also contained in PR #145

**Pull request closed without merging**
