### PR TITLE
Bootstrap

### PR DESCRIPTION
**Pull request by RoboSparrow**

### CODE REVIEW

**Comment by RoboSparrow** [comment]
@sraka1 Fixed some errors. I changed the handling of the slim container invocation in bootstrap so we don't need to hardcode slim defaults into the config.yml. [See changes](https://github.com/Brightcookie/lxHive/pull/125/commits/d5bd52d3e9209fb4c617938f295017814978ac1f#diff-3d9690b5093b22c1e92d3cb3f1c55f0fL234) Also introducing A new ExceptionType `AppInitException` for catching boot/config specific errors

**Comment by sraka1** [comment]
@RoboSparrow looks good in general, but see also other PR comment

**Comment by RoboSparrow** [comment]
@sraka1 I can see your point.
 However I don't think there is any harm in that. As long we don't publish all our unit tests /s we need to show that we are committed to testing. Don't forget also that we have a number of conformance test suites, include our own which we should make public soon. 
I plan to add a bash file for installing conformance the different suites and maybe some general docs in regards to versions and some stats of our coverage.

Also, tests like https://github.com/RoboSparrow/lxHive-dev/tree/28c42bc862301af993336a2b02aeb4dd0697d439/tests/Unit/Issue91 are PHPUnit , but not really *unit tests* as they test rather behaviours than atomic  functionalitties. Might migrate them if they are getting too many.

What do you think?

**Comment by sraka1** [comment]
@RoboSparrow Behavioural/function tests (like the Stream test) don't belong there. They should be moved to lx-Test-Suite. I am more inclined to include a couple commands like `./X test:functional`, `./X test:adl` and `./X test:all`. These commands would clone their respective test repositories and run the tests.

As for the `conformance` folder I still think it's redundant. You wrote the README in the `tests` folder which states `Folder bdd: You can safely load external BDD suites in this folder, they are excluded from commits by the local .gitignore`. I think that is a much better approach than having a separate root-level/top-level folder just for conformance tests.

**Comment by RoboSparrow** [comment]
@sraka1 Since I am writing tests I request the folder to stay. I have reasons to do so, I outlined some of them.

Feature tests **do** belong here, #91 being a good example. #91 is not a conformance issue, not a bug, but a feature problem. lxTest suite is node driven and works well for conformance and general REST testing, however testing *TinCanPHP* behaviour with javascript is just unrealistic.

Using the ./X console for something only a few developer will use is IMO an overkill. I will correct the readme tough, good point.

**Pull request merged**
