### PR TITLE
inherit permissions

### PR DESCRIPTION
**Pull request by RoboSparrow**
* simple permission matrix and lookup of child permissions
* `API\Console\BasicTokenCreateCommand`: load child permissions based on user permissions and display as selectable options.

see 

* https://github.com/Brightcookie/lxHive-Internal/issues/125
* https://github.com/Brightcookie/lxHive-Internal/issues/122

@sraka1 Please check carefully

### CODE REVIEW

**Comment by RoboSparrow** [comment]
see also master 

* https://github.com/Brightcookie/lxHive/pull/145/commits/7904d7468e22bf077889c1d06205e03472d92539
* https://github.com/Brightcookie/lxHive/pull/145/commits/94aa38ea65037c432d250fe954a01e964e8dbbfb

**Comment by RoboSparrow** [comment]
@sraka1 ?

**Comment by sraka1** [comment]
Closing this as all commits are also container in PR #147.

**Comment by sraka1** [comment]
Reopening and merging as #148 is under discussion. 

Looks good after going through it. One minor thing to note though - in `getChildrenFor` - the permissions matrix won't change much, so you didn't have to do nesting - (i.e. `all` contains `all/read` which then contains all the _simple/base_ permissions). 

I know it's only used in the X CLI at the moment, but I'm commenting just as a note if we ever call it from other places, we can improve speed a bit by simplifying this call.

**Comment by RoboSparrow** [comment]
TODO: 0.9.5 : https://github.com/Brightcookie/lxHive-Internal/issues/125

**Comment by RoboSparrow** [comment]
@sraka1 

> ... One minor thing to note though - in getChildrenFor - the permissions matrix won't change much, so you didn't have to do nesting - (i.e. all contains all/read which then contains all the simple/base permissions).

Generally agree, though I had in my mind that we make this configurable in future

**Pull request merged**
