### PR TITLE
Only add users' actual permissions as options for token creation

### PR DESCRIPTION
**Pull request by sraka1**

### CODE REVIEW

**Comment by RoboSparrow** [comment]
issue Brightcookie/lxHive-Internal#114

**Comment by RoboSparrow** [comment]
@sraka1 also implemented in development branch?

**Comment by RoboSparrow** [comment]
question:

what about 

oAuth token?
POST temporary token

**Comment by RoboSparrow** [comment]
tested current changes. Ok.

**Comment by sraka1** [comment]
Also inpl in development, just need to do a quick test. Will open a separate PR, closing this one.

**Pull request merged**
