### PR TITLE
Fix conflicts (ID rejection), also fix authority

### PR DESCRIPTION
**Pull request by sraka1**
Fixes statements with same ID to not be overwritten if they do not match exactly.

Also, fixes the authority (which wasn't added) in statements.

### CODE REVIEW

**Comment by RoboSparrow** [comment]
This fails with a `500`!

POST /statements with statementId

```
{
    "actor": {
        "mbox": "mailto:anonymous@lxhive.com"
    },
    "verb": {
        "id": "http://lxhive.com/verbs/lxtest/tested"
    },
    "object": {
        "id": "http://lxhive.com/activities/lxtest/statement/properties/id"
    },
    "id": "f04fd780-e641-4608-95c2-111d9acd8804"
}
```
response:
```
{
    "data": {
        "error_message": "Undefined variable: cursor"
    },
    "status": 500,
    "statusText": "Internal Server Error",
    "error": false,
    "headers": {... }
}
```

**Comment by sraka1** [comment]
Investigating. Worked in test I conducted earlier.

**Comment by RoboSparrow** [comment]
Here all tests/fails

ID
    POST /statements without statementId
      ✓ makes sure the test is valid
      ✓ MUST store a statement
    POST /statements with statementId
      ✓ makes sure the test is valid
      1) MUST store a statement
    Bad statement.id
      ✓ MUST reject PUT /statements BAD statementId: "bad" (539ms)
      ✓ MUST reject POST /statements BAD statementId (554ms)
      2) MUST reject GET /statements BAD statementId gracefully
      ✓ MUST reject GET /statements BAD voidedStatementId (520ms)
      ✓ MUST reject PUT /statements BAD statementId: "too short" (535ms)
      ✓ MUST reject POST /statements BAD statementId (546ms)
      ✓ MUST reject GET /statements BAD statementId gracefully (521ms)
      ✓ MUST reject GET /statements BAD voidedStatementId (521ms)
      ✓ MUST reject PUT /statements BAD statementId: "bang" (542ms)
      ✓ MUST reject POST /statements BAD statementId (557ms)
      3) MUST reject GET /statements BAD statementId gracefully
      ✓ MUST reject GET /statements BAD voidedStatementId (527ms)
      4) MUST reject PUT /statements BAD statementId: "non-hex characters"
      ✓ MUST reject POST /statements BAD statementId (544ms)
      5) MUST reject GET /statements BAD statementId gracefully
      ✓ MUST reject GET /statements BAD voidedStatementId (522ms)
      ✓ MUST reject PUT /statements BAD statementId: "your mom is not a GUID" (543ms)
      ✓ MUST reject POST /statements BAD statementId (543ms)
      6) MUST reject GET /statements BAD statementId gracefully
      ✓ MUST reject GET /statements BAD voidedStatementId (528ms)
      ✓ MUST reject PUT /statements BAD statementId: "null" (542ms)
      ✓ MUST reject POST /statements BAD statementId (541ms)
      7) MUST reject GET /statements BAD statementId gracefully
      ✓ MUST reject GET /statements BAD voidedStatementId (528ms)
      ✓ MUST reject PUT /statements BAD statementId: "empty string is not a GUID" (536ms)
      ✓ MUST reject POST /statements BAD statementId (545ms)
      8) MUST reject GET /statements BAD statementId gracefully
      ✓ MUST reject GET /statements BAD voidedStatementId (525ms)

**Comment by RoboSparrow** [comment]
thetest cases for invalid are mostly taken from http://guid.us/Test/GUID

**Comment by sraka1** [comment]
But there's checkmarks? Anyways, I tested with lx-Test-Suite as well. Maybe all the branches merged together broke something, it worked while it was branched off. Testing now.

**Comment by RoboSparrow** [comment]
The tests for BAD are basically that given a invalid uuid (BAD_ID)
* POST/PUT with BAD_ID MUSTreturn `400`, 
* GET with BAD_ID MUST return `404`

**Comment by sraka1** [comment]
That was resolved in a different PR (#73). This is just for rejecting statements with same ID (if they don't match).

**Comment by RoboSparrow** [comment]
well, i don't know -  at the end we have a 500 error and 7 other fails

**Comment by RoboSparrow** [comment]
with the "gracefully fails", I think this stems from previously run tests where POST/PUT BAD_ID passed (and was stored) Ignore them for now while I harden the test.

**Comment by RoboSparrow** [comment]
Ok, i randomized the test a bit more so that most BAD ids are unique to the test and should only get stored once a test fails:

here is the mocha stoud

```
  27 passing (14s)
  5 failing

  1) ID POST /statements with statementId MUST store a statement:

      AssertionError: response status: 200: expected 500 to equal 200
      + expected - actual

      -500
      +200
      
      at Function.assert.strictEqual (/var/www/html/lxHive/Tests/lx-Test-Suite/node_modules/chai/lib/chai/interface/assert.js:178:32)
      at Context.<anonymous> (specs/41-statement-properties/4101-id/id.js:92:20)

  2) ID Bad statement.id MUST reject PUT /statements BAD statementId: "non-hex characters":

      Uncaught AssertionError: response status: 400: expected 204 to equal 400
      + expected - actual

      -204
      +400
      
      at Function.assert.strictEqual (/var/www/html/lxHive/Tests/lx-Test-Suite/node_modules/chai/lib/chai/interface/assert.js:178:32)
      at Object.req.xapi.always (specs/41-statement-properties/4101-id/inc.bad-id.js:38:32)
      at IncomingMessage.<anonymous> (/var/www/html/lxHive/Tests/lx-Test-Suite/lxRequest/req.js:241:24)
      at endReadableNT (_stream_readable.js:906:12)

  3) ID Bad statement.id MUST reject GET /statements BAD statementId: "non-hex characters" gracefully:

      Uncaught AssertionError: response status: 404: expected 200 to equal 404
      + expected - actual

      -200
      +404
      
      at Function.assert.strictEqual (/var/www/html/lxHive/Tests/lx-Test-Suite/node_modules/chai/lib/chai/interface/assert.js:178:32)
      at Object.req.xapi.always (specs/41-statement-properties/4101-id/inc.bad-id.js:78:32)
      at IncomingMessage.<anonymous> (/var/www/html/lxHive/Tests/lx-Test-Suite/lxRequest/req.js:241:24)
      at endReadableNT (_stream_readable.js:906:12)

  4) ID Bad statement.id MUST reject GET /statements BAD statementId: "null" gracefully:

      Uncaught AssertionError: response status: 404: expected 200 to equal 404
      + expected - actual

      -200
      +404
      
      at Function.assert.strictEqual (/var/www/html/lxHive/Tests/lx-Test-Suite/node_modules/chai/lib/chai/interface/assert.js:178:32)
      at Object.req.xapi.always (specs/41-statement-properties/4101-id/inc.bad-id.js:78:32)
      at IncomingMessage.<anonymous> (/var/www/html/lxHive/Tests/lx-Test-Suite/lxRequest/req.js:241:24)
      at endReadableNT (_stream_readable.js:906:12)

  5) ID Bad statement.id MUST reject GET /statements BAD statementId: "empty string is not a GUID" gracefully:

      Uncaught AssertionError: response status: 404: expected 200 to equal 404
      + expected - actual

      -200
      +404
      
      at Function.assert.strictEqual (/var/www/html/lxHive/Tests/lx-Test-Suite/node_modules/chai/lib/chai/interface/assert.js:178:32)
      at Object.req.xapi.always (specs/41-statement-properties/4101-id/inc.bad-id.js:78:32)
      at IncomingMessage.<anonymous> (/var/www/html/lxHive/Tests/lx-Test-Suite/lxRequest/req.js:241:24)
      at endReadableNT (_stream_readable.js:906:12)
```

**Comment by RoboSparrow** [comment]
see https://github.com/Brightcookie/lx-Test-Suite/blob/master/src/specs/config/uuid.js

**Comment by sraka1** [comment]
This has been fixed.

However, for comparison of statements with same UUID, not all rules have been implemented.
They are described here: https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI-Data.md#231-statement-immutability

This is in the works.

**Comment by RoboSparrow** [comment]
https://github.com/Brightcookie/lxHive/pull/75 solves  GET statementId=<invalid> Even if a smt with an invalid made its way into our hive it should not be returned.

**Comment by RoboSparrow** [comment]
What is left is the FAIL for non-hex characters. `2075x932-9d7f-4aa9-93e8-7132b00e9479 204`. Not sure why this passes on PUT but not on POST

**Comment by RoboSparrow** [comment]
ok, I know whats wrong.. fixing

**Pull request merged**
