### PR TITLE
Issue #147 rfc2616 variants for authorization headers

### PR DESCRIPTION
**Pull request by RoboSparrow**
commit: https://github.com/Brightcookie/lxHive/commit/88c854c0a288ad92b02d0d0084a07b537dcdaae5

@sraka1 Please check. did manual testing,  The issue solves this only for basic and oAuth, but provides a convenience method `Resource::searchRequestHeaders` for other cases.

This needs also to be checked and implemented in development. Give us an estimate please

(includes changes from PR https://github.com/Brightcookie/lxHive/pull/145)

### CODE REVIEW

**Comment by RoboSparrow** [comment]
@sraka1 ?

**Comment by sraka1** [comment]
Slim (2) normalizes the header names (https://github.com/sraka1/Slim/blob/master/Slim/Http/Headers.php#L94). The only place where this would occur is rawHeaders and that is only used on multi-part requests, if I remember correctly. I think making an edit to the rawHeaders method would be better (to normalize the keys), since this is a method we added ourselves on the fork anyways (again, because of multipart requests).

**Comment by RoboSparrow** [comment]
Hmm, Slim 2 has removed the `rawHeaders` method. Both versions seem to UPPERCASE fields (which is an odd choice) in `Headers::createFromEnvironment()` [link](https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Headers.php#L51). However AFAIK this has no effect in 0.9.1 (tested that) and likely also in 0.9.5, maybe this needs to be invoked manually via middleware?

**Comment by RoboSparrow** [comment]
@sraka1 You aware that this PR wants to merge into **master**?

**Comment by RoboSparrow** [comment]
Also, this issue is not multipart-only. It's about conformance and compatibility: https://github.com/Brightcookie/lxHive/issues/147
Fixing this on master has a high priority. 

The important commit is https://github.com/Brightcookie/lxHive/pull/148/commits/88c854c0a288ad92b02d0d0084a07b537dcdaae5

**Comment by sraka1** [comment]
I understand that it's on master and a high priority fix, but I think a better solution would be to update our fork of Slim2 which introduced this problem in the first place (by not normalising header names in the rawHeaders method, like Slim does on the normal headers method.)

**Comment by RoboSparrow** [comment]
Is there any reason to keep the fork as it is extra maintain if we could just use a low level utils function, based on get_headers()?  We will still need to maintain 0.9.1 after the new release.

**Comment by RoboSparrow** [comment]
closing, resolved inhttps://github.com/Brightcookie/lxHive/pull/161

**Pull request closed without merging**
